/**
 * Types for Community RAG (Retrieval-Augmented Generation)
 * Feature: Community-RAG Integration (Vorschlag 15)
 *
 * Defines types for indexing community content (bulletin board posts,
 * replies, shakedowns) into vector embeddings for semantic search.
 */

// ============================================================================
// Source Content Types
// ============================================================================

export type CommunitySourceType =
  | 'bulletin_post'
  | 'bulletin_reply'
  | 'shakedown'
  | 'shakedown_feedback';

export interface CommunityChunk {
  /** Unique chunk ID (generated by DB) */
  id?: string;
  /** Type of source content */
  source_type: CommunitySourceType;
  /** ID of the source record */
  source_id: string;
  /** The text content of this chunk */
  chunk_text: string;
  /** Index within the source (0 for single-chunk posts) */
  chunk_index: number;
  /** Author of the original content */
  author_id: string | null;
  /** Tags from the post (e.g., ['gear_advice', 'question']) */
  tags: string[];
  /** Extracted gear/product names mentioned in the content */
  gear_names: string[];
  /** Extracted brand names mentioned in the content */
  brand_names: string[];
  /** When the source content was created */
  source_created_at: string | null;
}

// ============================================================================
// Search Types
// ============================================================================

export interface CommunitySearchResult {
  id: string;
  source_type: CommunitySourceType;
  source_id: string;
  chunk_text: string;
  tags: string[];
  gear_names: string[];
  brand_names: string[];
  author_id: string | null;
  source_created_at: string | null;
  similarity: number;
}

export interface CommunitySearchOptions {
  /** Maximum number of results to return */
  topK?: number;
  /** Minimum similarity threshold (0-1, default 0.65) */
  threshold?: number;
  /** Filter by source type */
  sourceType?: CommunitySourceType;
  /** Filter by tags (returns results matching ANY of the given tags) */
  tags?: string[];
}

// ============================================================================
// Indexing Types
// ============================================================================

export interface IndexingResult {
  /** Number of chunks successfully indexed */
  indexed: number;
  /** Number of chunks that failed */
  failed: number;
  /** Number of chunks skipped (already up to date) */
  skipped: number;
  /** Error messages for failed chunks */
  errors: string[];
}

export interface BulletinPostForIndexing {
  id: string;
  content: string;
  tag: string | null;
  author_id: string;
  created_at: string;
  author_name?: string;
  reply_count?: number;
}

export interface BulletinReplyForIndexing {
  id: string;
  post_id: string;
  content: string;
  author_id: string;
  created_at: string;
  author_name?: string;
}

// ============================================================================
// Configuration
// ============================================================================

export const COMMUNITY_RAG_CONFIG = {
  /** Maximum chunk size in characters */
  MAX_CHUNK_SIZE: 1500,
  /** Overlap between chunks in characters */
  CHUNK_OVERLAP: 200,
  /** Minimum content length to index */
  MIN_CONTENT_LENGTH: 20,
  /** Default similarity threshold */
  DEFAULT_THRESHOLD: 0.65,
  /** Default number of results */
  DEFAULT_TOP_K: 5,
  /**
   * Embedding model to use.
   * NOTE: This model produces 1536-dimensional vectors, which must match the
   * `vector(1536)` column in the community_knowledge_chunks migration.
   * If you change this model, create a new migration to alter the column and
   * rebuild the HNSW index — existing embeddings will be incompatible.
   */
  EMBEDDING_MODEL: 'openai/text-embedding-3-small',
  /** Batch size for bulk indexing */
  BATCH_SIZE: 50,
} as const;
