#!/bin/bash

# Auto-Build Environment Setup - Gear Quantity Tracking
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Feature: Gear Quantity Tracking"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}ERROR: Node.js is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js found: $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}ERROR: npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm found: $(npm --version)${NC}"

# Check for .env.local
if [ ! -f .env.local ]; then
    echo -e "${YELLOW}WARNING: .env.local not found${NC}"
    echo "Copy .env.example to .env.local and configure environment variables"
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
npm install

# ============================================
# START MAIN SERVICE
# ============================================

echo ""
echo "Starting Next.js development server..."
npm run dev &
DEV_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js (main)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Main (Next.js):  http://localhost:3000"
echo ""
echo "Feature: Gear Quantity Tracking"
echo "  - Add quantity field to gear form"
echo "  - Display quantity badges on inventory cards"
echo "  - Validate quantity in loadout builder"
echo "  - Update weight calculations to multiply by quantity"
echo ""
echo "Key URLs:"
echo "  - Gear Form:       http://localhost:3000/inventory/new"
echo "  - Inventory View:  http://localhost:3000/inventory"
echo "  - Loadouts:        http://localhost:3000/loadouts"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running
wait $DEV_PID
