/**
 * Pending Confirmations Store
 * Feature: Suspend/Resume for Human-in-the-Loop Actions
 *
 * Durable store for tracking suspended workflow runs awaiting user confirmation.
 * Backed by Supabase (pending_confirmations table) to survive across serverless
 * function invocations — the in-memory Map approach fails when Vercel routes the
 * chat request and the resume request to different instances.
 *
 * This implements the "suspend" side of Mastra's suspend/resume pattern:
 * the workflow pauses here, and the resume API endpoint continues execution.
 *
 * @see https://mastra.ai/docs/workflows/suspend-and-resume
 */

import { createServiceRoleClient } from '@/lib/supabase/server';
import { logInfo, logWarn, logError } from '@/lib/mastra/logging';

// =============================================================================
// Types
// =============================================================================

/**
 * Data stored when a workflow suspends for user confirmation
 */
export interface PendingConfirmation {
  /** Unique ID for this pending confirmation */
  runId: string;
  /** User who initiated the action */
  userId: string;
  /** Step that suspended (e.g., 'confirmAdd') */
  suspendedStepId: string;
  /** Human-readable confirmation message */
  message: string;
  /** Payload needed to resume execution */
  payload: AddGearPayload;
  /** When the confirmation was created */
  createdAt: Date;
  /** TTL: confirmation expires after this timestamp */
  expiresAt: Date;
  /** Current status */
  status: 'pending' | 'approved' | 'cancelled' | 'expired';
}

/**
 * Payload for add-gear-to-loadout confirmation
 */
export interface AddGearPayload {
  gearItemId: string;
  gearItemName: string;
  loadoutId: string;
  loadoutName: string;
  quantity: number;
  worn: boolean;
  consumable: boolean;
}

/**
 * Result of a resume operation
 */
export interface ResumeResult {
  success: boolean;
  message: string;
  loadoutItemId?: string;
  updatedTotalWeight?: number;
  error?: string;
}

// =============================================================================
// Constants
// =============================================================================

/** Confirmation TTL in milliseconds (5 minutes) */
const CONFIRMATION_TTL_MS = 5 * 60 * 1000;

// =============================================================================
// Database row type
// =============================================================================

/** Shape of a row in the pending_confirmations table */
interface DbPendingConfirmation {
  run_id: string;
  user_id: string;
  suspended_step: string;
  message: string;
  payload: AddGearPayload;
  created_at: string;
  expires_at: string;
  status: 'pending' | 'approved' | 'cancelled' | 'expired';
}

/** Map a DB row to the application type */
function fromDbRow(row: DbPendingConfirmation): PendingConfirmation {
  return {
    runId: row.run_id,
    userId: row.user_id,
    suspendedStepId: row.suspended_step,
    message: row.message,
    payload: row.payload as AddGearPayload,
    createdAt: new Date(row.created_at),
    expiresAt: new Date(row.expires_at),
    status: row.status,
  };
}

// =============================================================================
// Store Implementation (Supabase-backed)
// =============================================================================

/**
 * Create a new pending confirmation (suspend workflow)
 *
 * @param userId - Authenticated user ID
 * @param payload - Gear/loadout details for the action
 * @param message - Human-readable confirmation message
 * @returns The created PendingConfirmation with runId
 */
export async function suspendForConfirmation(
  userId: string,
  payload: AddGearPayload,
  message: string
): Promise<PendingConfirmation> {
  const now = new Date();
  const expiresAt = new Date(now.getTime() + CONFIRMATION_TTL_MS);

  const supabase = createServiceRoleClient();

  // run_id is generated by Supabase (gen_random_uuid() default)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (supabase as any)
    .from('pending_confirmations')
    .insert({
      user_id: userId,
      suspended_step: 'confirmAdd',
      message,
      payload,
      created_at: now.toISOString(),
      expires_at: expiresAt.toISOString(),
      status: 'pending',
    })
    .select()
    .single() as { data: DbPendingConfirmation | null; error: Error | null };

  if (error || !data) {
    logError('[PendingConfirmations] Failed to insert confirmation', error, {
      metadata: { item: payload.gearItemName, loadout: payload.loadoutName },
    });
    throw new Error(`Failed to store pending confirmation: ${error?.message ?? 'Unknown error'}`);
  }

  logInfo('[PendingConfirmations] Suspended', {
    metadata: { runId: data.run_id, item: payload.gearItemName, loadout: payload.loadoutName },
  });

  return fromDbRow(data);
}

/**
 * Get a pending confirmation by runId
 *
 * @param runId - The workflow run ID
 * @returns The PendingConfirmation or null if not found/expired
 */
export async function getConfirmation(runId: string): Promise<PendingConfirmation | null> {
  const supabase = createServiceRoleClient();

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (supabase as any)
    .from('pending_confirmations')
    .select('*')
    .eq('run_id', runId)
    .eq('status', 'pending')
    .gt('expires_at', new Date().toISOString())
    .maybeSingle() as { data: DbPendingConfirmation | null; error: Error | null };

  if (error) {
    logError('[PendingConfirmations] Failed to fetch confirmation', error, {
      metadata: { runId },
    });
    return null;
  }

  return data ? fromDbRow(data) : null;
}

/**
 * Mark a confirmation as approved or cancelled (resume workflow).
 * Uses an atomic UPDATE … WHERE to prevent race conditions.
 *
 * @param runId - The workflow run ID
 * @param userId - The user performing the action (must match original user)
 * @param approved - Whether the user approved or cancelled
 * @returns The updated confirmation, or null if not found/unauthorized/expired
 */
export async function resolveConfirmation(
  runId: string,
  userId: string,
  approved: boolean
): Promise<PendingConfirmation | null> {
  const supabase = createServiceRoleClient();
  const newStatus = approved ? 'approved' : 'cancelled';

  // Atomic update: only succeeds if run_id + user_id + status='pending' + not expired all match.
  // This prevents cross-user attacks and double-resolution without a separate check.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (supabase as any)
    .from('pending_confirmations')
    .update({ status: newStatus })
    .eq('run_id', runId)
    .eq('user_id', userId)
    .eq('status', 'pending')
    .gt('expires_at', new Date().toISOString())
    .select()
    .maybeSingle() as { data: DbPendingConfirmation | null; error: Error | null };

  if (error) {
    logError('[PendingConfirmations] Failed to resolve confirmation', error, {
      metadata: { runId, userId, approved },
    });
    return null;
  }

  if (!data) {
    // No rows updated — could be wrong user, already resolved, or expired
    logWarn('[PendingConfirmations] Resolve matched no rows', {
      metadata: { runId, userId },
    });
    return null;
  }

  logInfo(`[PendingConfirmations] Resolved: status=${newStatus}`, {
    metadata: { runId },
  });

  return fromDbRow(data);
}
