-- Migration: Consolidated into 20260226000001_catalog_search_enrichment.sql
--
-- This migration was originally used to add brand_name to the search_catalog_enriched()
-- return columns (via LEFT JOIN catalog_brands). Since both migrations were developed
-- before being deployed to any environment, they were consolidated into migration 000001
-- to avoid the DROP + CREATE churn and produce a cleaner schema history.
--
-- See: 20260226000001_catalog_search_enrichment.sql for the full final schema.
--
-- This file is intentionally empty (no-op) to preserve migration sequence numbering.
